---
#- hosts: master
# remote_user: vagrant

# - tasks:
- name: install_apache2
  package:
    name: apache2
    state: present
  tags: master
  
- name: update_apache2_config_file
  template:
    src: roles/master/templates/httpd.j2
    dest: /etc/httpd.conf
  notify:
  - restart_apache

- name: update_host_name
  template:
    src: roles/master/templates/hostname.j2
    dest: /etc/hostname

- name: enable_apache
  service:
    name: apache2
    state: started
    enabled: yes